### ISSUE TITLE
ateliers/snake: Proposition de simplification de l'atelier

### ISSUE THREAD

**Issue by A-312** [zestedesavoir/zestedecode#5]
J'ai vu ce passage : 

```
# Fonction principale d'initialisation
def initialisation(jeu):
	# Création d'un serpent à l'écran
	jeu.serpent = Serpent()

	# (SO1) Donne une direction par défaut au serpent
	jeu.direction_serpent = jeu.serpent.DIRECTIONS.STOP

	# Déclaration du cactus
	jeu.ajouter_image("Cactus", "images/cactus.png")

	# Ajout du corps
	jeu.ajouter_image("Corps", "images/corps.png")
	# Ajout de la queue
	jeu.ajouter_image("Queue", "images/queue.png")
	# Ajout de la tête
	jeu.ajouter_image("Tête", "images/tete.png")

	# Ajout de l'asset spécial qui sera automatiquement mis en fond
	jeu.ajouter_image("fond", "images/fond.png")
```

Ne serait-il pas plus simple de dire que toutes les images dans `images/` sont ajoutés automatiquement et qu'il suffira simplement d'utiliser le nom des images?

Ou simplement préciser le dossier : 
```
	jeu.ajouter_image("images/")
```

Je sais que souvent les débutants ont peur quand il y a beaucoup de ligne, ces lignes me semblent facultatives. Je suis conscient que le chargement des ressources est une phases très importante dans l'utilisation de librairie graphique, mais est-ce vraiment utile d'ajouter une difficulté sur le chargement ?

**Comment by TitiAlone** [comment]
Plutôt contre là comme ça, parce que si on abstrait tout, il ne reste plus rien, mais pas complètement fermé sur l'idée, à voir avec les autres.

**Comment by Situphen** [comment]
Comme je l'ai dit sur IRC, en effet ça permet de simplifier mais ça empêche les apprenants de se tromper en oublier d'écrire le petit bout de code qui ajoute une nouvelle image. Et puis il y a plusieurs lignes `jeu.ajouter_image("Cactus", "images/cactus.png")` mais c'est un seul concept, ça ne rajoute pas en complexité je trouve.

**Comment by AmauryCarrade** [comment]
Comme dit sur Discord : je suis aussi circonspect, car faire ça c'est perdre en explicite.

Je pense qu'il faut à tout prix éviter le côté _magie_ du code, car c'est pas très pédagogique. Et expliciter permet de clarifier les choses (le nom des images est écrit dans le code, ce qui n'est pas le cas avec un import par dossier), et de leur permettre de se tromper (en oubliant une image qui ne s'affiche du coup pas, ce qui permet de trouver l'erreur et de la corriger, ce qu'est formateur !) — comme @Situphen le soulignait, pour ce dernier point.

Donc, mitigé, même si je comprends l'idée derrière et que je ne suis pas non plus strictement opposé.

Et @Situphen me double encore à dix secondes près, grrr.
